#!/bin/sh
start-dunst
RESTART=0
[ "$1" = "--restart" ] && RESTART=1

manage() {
        PROG=$1
        if [ $RESTART -eq 1 ]
        then
                pidof "$PROG" && killall "$PROG"
                while pgrep -x "$PROG" >/dev/null; do sleep 1; done
        fi
        [ $RESTART -eq 0 ] && pidof "$PROG"
}

manage xss-lock || xss-lock -n '/usr/lib/xsecurelock/dimmer' -l -- 'screen-lock' &
manage sxhkd || sxhkd &
manage picom || picom &
manage polybar || polybar main &
manage syncthing || syncthing -no-browser &
manage kdeconnectd || /usr/lib/kdeconnectd &

kill $(pgrep -fl autopauseD | awk '{print $1}') 2>/dev/null ; autopauseD &
kill $(pgrep -fl bspswallow | awk '{print $1}') 2>/dev/null ; bspswallow &

xset s 300 5

while true; do pidof polybar && break; sleep 1; done;
while true; do pidof dunst && break; sleep 1; done;
notify-send -i xterm Luna READY!

