#!/bin/sh
dbus-daemon --session --address=unix:path="$XDG_RUNTIME_DIR/bus" &
. "$LUNA_COLOR_PATH/colors.sh"

run() {
 if ! pgrep $1 ;
  then
    $@&
  fi
}

dbus-update-activation-environment --systemd --all
systemctl start --user pipewire-pulse.service
xset s 180
xsetroot -name "Loading..."

run unclutter
run dbus-launch --exit-with-x11
#run playerctld
#run urxvtd
#run notifyd
run autopauseD
run dunst
#run syncthing -no-browser
run xss-lock -- screen-lock -n


{ while [ -z "$(pactl info)" ]; do
        sleep 0.2
done && { pgrep -f "launch-bar-dwm" || launch-bar-dwm; }; } &

while [ 1 ]; do
  dwm
done
