#!/bin/sh
start-dunst
RESTART=1
[ "$1" = "--restart" ] && RESTART=1

manage() {
        PROG=$1
        if [ $RESTART -eq 1 ]
        then
                pidof "$PROG" && killall -qw "$PROG"
                return 1
        fi
        [ $RESTART -eq 0 ] && pidof "$PROG" && return 0
        return 1
}

manage xss-lock || xss-lock -n '/usr/lib/xsecurelock/dimmer' -l -- 'screen-lock' &
manage picom || picom &
manage polybar || polybar main &
/usr/lib/kdeconnectd &

kill "$(pgrep -fl autopauseD | awk '{print $1}')" 2>/dev/null ; autopauseD &
xset s 300 5

while true; do pidof polybar && break; sleep 1; done
while true; do pidof dunst && break; sleep 1; done
notify-send -i xterm Luna READY!
wait
