#!/bin/sh

userresources="$XDG_CONFIG_HOME/X11/.Xresources"
colorresources="$LUNA_COLOR_PATH/colors.Xresources"
usermodmap="$HOME/X11/.Xmodmap"
sysresources='/etc/X11/xinit/.Xresources'
sysmodmap='/etc/X11/xinit/.Xmodmap'
userautostart="$XDG_CONFIG_HOME/X11/autostart"
export PULSE_LATENCY_MSEC=100

# merge in defaults and keymaps

[ -f "$sysresources" ] && xrdb -merge "$sysresources"
[ -f "$userresources" ] && xrdb -merge "$userresources"
[ -f "$colorresources" ] && xrdb -merge "$colorresources"

[ -f "$sysmodmap" ] && xmodmap "$sysmodmap"
[ -f "$usermodmap" ] && xmodmap "$usermodmap"

{
        feh --no-fehbg --bg-scale "$LUNA_WALL_PATH"
        xsetroot -cursor_name left_ptr
        setxkbmap -option caps:escape
        start-dunst

        xset s 300 5
        while [ 1 ]; do
               dbus-run-session "$HOME/.config/X11/autolaunch";
        done

} > "$XDG_CACHE_HOME/x11_wm.1" 2> "$XDG_CACHE_HOME/x11_wm.2"
