# Shell variables
# Generated by 'wal'
wallpaper='/home/rohnch/.config/luna_theme/WALL.jpg'

# Special
background='#080908'
foreground='#dbdddc'
cursor='#dbdddc'

# Colors
color0='#080908'
color1='#bfc431'
color2='#3258cb'
color3='#3a7acd'
color4='#4b62d2'
color5='#dbdb70'
color6='#a7e598'
color7='#dbdddc'
color8='#999a9a'
color9='#bfc431'
color10='#3258cb'
color11='#3a7acd'
color12='#4b62d2'
color13='#dbdb70'
color14='#a7e598'
color15='#dbdddc'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
