# Shell variables
# Generated by 'wal'
wallpaper='/home/rohnch/.config/luna_theme/WALL.jpg'

# Special
background='#20131f'
foreground='#e1cbc2'
cursor='#e1cbc2'

# Colors
color0='#20131f'
color1='#B46250'
color2='#956961'
color3='#AC8679'
color4='#D7AD72'
color5='#B57684'
color6='#C7AA9B'
color7='#e1cbc2'
color8='#9d8e87'
color9='#B46250'
color10='#956961'
color11='#AC8679'
color12='#D7AD72'
color13='#B57684'
color14='#C7AA9B'
color15='#e1cbc2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
