# Shell variables
# Generated by 'wal'
wallpaper='/home/rohnch/.config/luna_theme/WALL.jpg'

# Special
background='#080F37'
foreground='#afbbcc'
cursor='#afbbcc'

# Colors
color0='#080F37'
color1='#2F4775'
color2='#A24952'
color3='#E85D5A'
color4='#295890'
color5='#5A6E9E'
color6='#007CC3'
color7='#afbbcc'
color8='#7a828e'
color9='#2F4775'
color10='#A24952'
color11='#E85D5A'
color12='#295890'
color13='#5A6E9E'
color14='#007CC3'
color15='#afbbcc'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
