#!/usr/bin/env sh
# Set as a cron job to check for new RSS entries for newsboat.
# If newsboat is open, sends it an "R" key to refresh.

ping -q -c 1 1.1.1.1 > /dev/null || exit

/usr/bin/notify-send -i internet-news-reader "Updating RSS feeds..."

pgrep -x newsboat >/dev/null && /usr/bin/xdotool key --window "$(/usr/bin/xdotool search --name newsboat)" v+l+R && /usr/bin/xdotool key --window "$(/usr/bin/xdotool search --name newsboat)" v+j+j+j+j+j+l

/usr/bin/newsboat -x reload
/usr/bin/notify-send  -i internet-news-reader "RSS feed update complete."
