#!/bin/sh
# shellcheck disable=SC2139
alias ls="ls --group-directories-first --color=auto -v"
alias grep="grep --color"
alias ll="ls -lh"
alias l="ls -lahv"
alias zathura="zathura"
alias p="sudo pacman"
alias vim='$EDITOR'
alias d='doas'
alias v='$EDITOR'
alias dv='d $EDITOR'
alias py='python'
alias nb='newsboat'
alias pypad='vim /tmp/pypad.py'
alias wget='wget --hsts-file="$XDG_CACHE_HOME/wget-hsts"'
alias o="xdg-open"
alias octave="octave -f"
alias oc="/usr/bin/octave -q"


# Network Manager
alias wifi='nmcli d wifi'
alias lw='nmcli d wifi list'
alias rad='nmcli r'

# startx
alias sX="startx -c $HOME/.config/X11/xinitrc"

# youtube-dl
alias ytv="youtube-dl --add-metadata -f 'bestvideo[height<=$LUNA_YPLAY_RES]+bestaudio' -o '%(title)s.%(ext)s'"
alias yta="youtube-dl --format=bestaudio --extract-audio --audio-format=opus --add-metadata -o '%(title)s.%(ext)s'"
alias ytm="youtube-dl --format=bestaudio --extract-audio --audio-format=opus --add-metadata --output='$LUNA_MUSIC_DIR/%(title)s.%(ext)s'"
alias crontab="crontab -i"
alias opennas="grep -q 'nas' /proc/mounts  || mount -a && cd /nas/"

sendit() {
        file_to_send="-"
        [ -n "$1" ] && file_to_send="$1"
        curl --progress-bar -F "file=@$file_to_send" https://0x0.st
}


slect() {
        echo "$1" | dmenu -i -p "$2 " -b -l 10 | { read -n selected && [ -n "$selected" ] && "$2" "$selected" && unset selected; }
}

fslect() {
        slect "$(ls -a1)" "$1"
}

ghc() {
		git clone git@github.com:"$*".git
}
