#!/bin/sh

. "${HOME}/.cache/wal/colors.sh"
killall dunst
dunst -nb "$background" -nf "$foreground" -cb "$background" -cf "$foreground" -lb $background -lf $foreground &

#Polybar
sh ~/scripts/system_managment/launch_polybar.sh
sleep 1

killall picom
picom &

killall nm-applet
nm-applet &

killall kdeconnect-indicator
kdeconnect-indicator &

killall xss-lock
xss-lock i3lock-next "Welcome Back, Liupold." "Fira Code" &

#volume
pactl set-sink-volume 0 80%

#cursor
xsetroot -cursor_name left_ptr
notify-send "Ready!"
