#! /bin/sh

if [ -z $(pidof sxhkd) ]
then
	sxhkd &
fi

# Set environment
export BSPWM_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/bspwm"

# WorkSpace / Monitor
bspc monitor -d I II III IV V VI VII VIII IX X


######################################################################

#----------------------------- BASIC ATTR ----------------------------


bspc config border_width        	1
bspc config window_gap          	8
bspc config top_padding         	0

bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_follows_pointer       true


bspc config split_ratio          	0.50
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true


#----------------------------- COLORS --------------------------------

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"

#----------------------------- RULES ---------------------------------

bspc rule -a Gimp state=floating follow=on
bspc rule -a Zathura state=tiled
bspc rule -a Screenkey manage=off


#--------------------------- CHAIN LOAD ------------------------------
# Autostart
sh "$BSPWM_CONFIG/autostart" &
