# Shell variables
# Generated by 'wal'
wallpaper='/home/rohnch/.config/WALL'

# Special
background='#0c0a09'
foreground='#cbdadd'
cursor='#cbdadd'

# Colors
color0='#0c0a09'
color1='#778476'
color2='#AB9253'
color3='#53768A'
color4='#6798AB'
color5='#73B0C8'
color6='#93A9AB'
color7='#cbdadd'
color8='#8e989a'
color9='#778476'
color10='#AB9253'
color11='#53768A'
color12='#6798AB'
color13='#73B0C8'
color14='#93A9AB'
color15='#cbdadd'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
