#!/bin/sh
WALL_PATH="$HOME/Walls"
src_link="https://wallhaven.cc/random"

id=$(wget "$src_link" -O - 2>/dev/null | grep -o 'https://wallhaven.cc/w/......' | head -1 | sed -e 's|https://wallhaven.cc/w/||g')
filename="$HOME/.cache/wall-rand"
[ "$1"  = "-dl" ] && filename="$WALL_PATH/wallhaven-$id.jpg"
wget -O - "https://wallhaven.cc/api/v1/w/$id" 2>/dev/null | jq '.data.path' | xargs -i wget -O "$filename" {} 2>/dev/null
[ "$1" != "-dl" ] && wal -c && setbg "$filename" 1>/dev/null
echo "$filename"
