#!/bin/sh
sh ~/scripts/system_managment/launch_polybar.sh
sh ~/scripts/system_managment/start-dunst
RESTART=0
[ "$1" = "--restart" ] && RESTART=1

manage() {
        PROG=$1
        [ $RESTART -eq 1 ] && pidof $PROG && killall $PROG
        [ $RESTART -eq 0 ] && pidof $PROG
}

manage xss-lock || xss-lock -n /usr/lib/xsecurelock/dimmer -l -- ~/scripts/system_managment/screen-lock &
manage sxhkd || sxhkd &
manage picom || picom &
manage nm-applet || nm-applet &
manage kdeconnect-indicator || kdeconnect-indicator &
manage xfce4-power-manager || xfce4-power-manager &
manage syncthing || syncthing -no-browser > /dev/null &
kill $(pgrep -fl Pause_D.sh | awk '{print $1}') 2>/dev/null ; sh ~/scripts/tools/Pause_D.sh &

xset s 300 5

while [ 1 ]; do [ ! -z $(pidof polybar) ] && break; sleep 1; done;
while [ 1 ]; do [ ! -z $(pidof dunst) ] && break; sleep 1; done;
notify-send -i xterm Luna READY!

