#!/bin/sh

function wait_for_launch {
        target="$1"
        while [ -z "$(pidof $target)" ]
        do
                python -c 'from time import sleep; sleep(0.01667)'
        done

}


function if_start {
        _target=$1
        target=$2

        if [ -z $target ]
        then
                eval $_target &
        else
                if [ -z "$(pidof $_target)" ]
                then
                        eval $target &
                fi
        fi
}

sh ~/scripts/system_managment/start-dunst
wait_for_launch dunst

if_start picom picom
if_start sxhkd sxhkd

sh ~/scripts/system_managment/launch_polybar.sh
if_start nm-applet nm-applet
if_start kdeconnect-indicator kdeconnect-indicator

if_start xss-lock "xss-lock i3lock-next \"Welcome Back, Liupold.\" \"Fira Mono\""
xfce4-power-manager

# waiting for launch
wait_for_launch sxhkd
wait_for_launch polybar

notify-send -i xterm "READY!"
