#!/bin/sh

if [ -e "${HOME}/.cache/wal/colors.sh" ]
then
        # source the colors.
        . "${HOME}/.cache/wal/colors.sh"

fi
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"
