#!/bin/sh

function wait_for_launch {
        target="$1"
        while [ -z "$(pidof $target)" ]
        do
                python -c 'from time import sleep; sleep(0.01667)'
        done

}


function if_start {
        _target=$1
        target=$2

        if [ -z $target ]
        then
                eval $_target &
        else
                if [ -z "$(pidof $_target)" ]
                then
                        eval $target &
                fi
        fi
}

if_start sxhkd sxhkd

if_start xss-lock "xss-lock -n /usr/lib/xsecurelock/dimmer -l -- ~/scripts/system_managment/screen-lock &"

if_start picom picom
sh ~/scripts/system_managment/launch_polybar.sh
if_start nm-applet nm-applet
if_start kdeconnect-indicator kdeconnect-indicator

xfce4-power-manager

kill $(pgrep -fl Pause_D.sh | awk '{print $1}') 2>/dev/null
sh ~/scripts/tools/Pause_D.sh

# waiting for launch
wait_for_launch sxhkd
wait_for_launch polybar

xset s 300 5
notify-send -i xterm "READY!"
