#!/bin/sh
[ -f "${HOME}/.cache/wal/colors.sh" ] && . "${HOME}/.cache/wal/colors.sh"

export XSECURELOCK_AUTH_BACKGROUND_COLOR="$background"
export XSECURELOCK_AUTH_FOREGROUND_COLOR="$foreground"
export XSECURELOCK_PASSWORD_PROMPT="time"
export XSECURELOCK_LIST_VIDEOS_COMMAND="find ~/Walls/LockVid"
export XSECURELOCK_SAVER="saver_mpv"
export XSECURELOCK_SHOW_DATETIME=1
export XSECURELOCK_NO_COMPOSITE=1 # till picom is supported


[ "$(playerctl status)" = "Playing" ] || xsecurelock
[ "$1" = "--force" ] && xsecurelock
