name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: sourcing dots.sh
      run: . ./dots.sh

    - name: Testing dls
      run: echo "$dot_all"

    - name: Testing dls
      run: ./dls -vS "$dot_all"
